version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    docker:
      - image: cimg/node:17.7.1
    steps:
      - checkout
      - run:
          command: sudo npm i -g serverless npm@latest
      - run:
          command: ls
      - run:
          command: pwd
     # - run:
     #     command: npm i --save
     # - run:
     #     command: npm install 

            #- run:
            #command: chmod +x ./.circleci/install-credentials.sh
            #- run:
            #command: ./.circleci/install-credentials.sh
            # - run:
            #command: sls deploy

workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy:
              context: serverlessProject
